### ISSUE TITLE
companyweb_base: why no cron to auto-update data?

### ISSUE THREAD

**Issue by Yenthe666** [OCA/l10n-belgium#115]
Hi there @xavier-bouquiaux & @sbidoul,

First of all a BIG thank you for the Companyweb / Odoo connector :) 
I was wondering one thing. Why is there no cron job that automatically updates all companies every x time so they're auto updated?

Regards,
Yenthe

**Comment by sbidoul** [comment]
Hi @Yenthe666 The UX is based on recommendation from companyweb. IIRC a cron is not recommended to avoid consuming credits unexpectedly. We can double check with them.

**Comment by Yenthe666** [comment]
@sbidoul thanks a lot for the feedback! I was looking at https://www.companyweb.be/integrations/37/odoo?page=integrations-discover and https://www.companyweb.be/nl/order however, I don't see any mentions anywhere from any credit limits though?
Could you perhaps reach out to Companyweb to figure this out? Perhaps something is undocumented 🤔
