### ISSUE TITLE
companyweb

### ISSUE THREAD

**Issue by luc-demeyer** [OCA/l10n-belgium#14]
I tested the module. Nice work ! Thanks.
A few minor remarks:
- 'XML-access Not Activated' error message when trying to connect the first time. It would useful to update the module documentation (or the error message) to say that you need contact companyweb in order to get the XML access activated
- Adding some help on the 'Update' button would be good (to say that this button updates the partner record with the info retrieved from Companyweb). A useful enhancement would also be to show which fields will be updated before doing the update (updating credit limit, address info, .. without warning may break some processes in Odoo or in other systems).
- Extending the functionality to retrieve the VAT number from the company name would also be a nice enhancement.

**Comment by jrial** [comment]
Luc,

This should be 3 separate issues, so that each separate concern can have its issue closed when/if it's implemented.

**Comment by sbidoul** [comment]
The companyweb module as been rewritten from scratch following UX guidelines from Companyweb. It is maintained for 12, 13, 14. Therefore closing this.
