### ISSUE TITLE
In which modules should I add new mis-reports templates?

### ISSUE THREAD

**Issue by victor-champonnois** [OCA/l10n-belgium#185]
An accountant has made fixed and improved versions of mis-reports templates (Balance sheet and P&L) for specific legal form:
- a set of template for "Sociétés sans capital" (cooperatives, SRL)
- a set of templates for ASBL

We want to put them in modules in this repo. Should we add two new modules (one for each legal form) ? Or should we add them in the existing module of templates ?
@sbidoul @vdewulf

**Comment by sbidoul** [comment]
@victor-champonnois I think the best is to add them into the existing module.

By the way, we have an intern currently working on generating the P&L and BS templates from the XBRL taxonomy. A PR may arrive soon. cc/ @ThomasBinsfeld @mathisjacoby
