### ISSUE TITLE
account_companyweb question: local storage of barometer images?

### ISSUE THREAD

**Issue by jrial** [OCA/l10n-belgium#31]
Not so much an issue as a question.

I'm currently working on implementing a mass update for a customer and I'm hitting the rate limit of the companyweb servers when fetching the barometer images.

I am currently preparing 2 pull requests that will solve some issues I noticed with the module.

While I'm at it, I might as well create a third PR to add all the barometer images and fetch them from the local filesystem rather than over http. There are 102 new ones in addition to the already existing barometer_none but the complete set weighs in at 1.7MB vs. the 16kB that barometer_none occupies now. Not sure if this is worth adding to the module. On one hand, it does save a lot of network traffic when doing mass updates and saves you from the dreaded "connection refused". On the other hand, it would grow the module from 376kB to 2.1MB, which is a non-significant increase.

Thoughts?

**Comment by sbidoul** [comment]
@jrial I'd like to draw you attention to https://github.com/OCA/l10n-belgium/pull/28. You'll probably want to review that one and base your work on it.

**Comment by jrial** [comment]
@sbidoul : thanks for the info, closing this issue.
