### ISSUE TITLE
Missing labels *needs fixing* and *needs review*

### ISSUE THREAD

**Issue by yvaucher** [OCA/l10n-belgium#5]
Read OCA/maintainers-tools#29 to know more about it

**Comment by sbidoul** [comment]
I don't have rights to create labels. Can you do it?

**Comment by yvaucher** [comment]
I can't I already did it for all other repo with the script proposed here
https://github.com/OCA/maintainers-tools/pull/30

**Comment by sbidoul** [comment]
ok, thanks for the pointer.

I created the labels for l10n-belgium as well as l10n-luxemburg
