### ISSUE TITLE
Not able to set bba as default value

### ISSUE THREAD

**Issue by tycho91** [OCA/l10n-belgium#67]
Hello, 

I'm on Odoo version 9.0 and I've just added the addon.
My issue is that setting "bba" as a default value when creating an invoice does not work. It is correct in the defaults list but it keeps selecting "Free communication" by default making me edit every invoice before confirming.

Kind regards

**Comment by sbidoul** [comment]
If I remember correctly, the default value is set on the partner, can you check that?

**Comment by luc-demeyer** [comment]
When selecting a partner on the invoice the 'onchange_partner_id' method will set the communication type  based upon the partner settings.
