### ISSUE TITLE
[10.0] Balance sheet is wrong for accounts in foreign currencies

### ISSUE THREAD

**Issue by fdegrave** [OCA/l10n-belgium#73]
I don't know if I miss something, but it seems the balance of accounts in foreign currencies is wrong in the balance sheet. Indeed, it computes the sum of the transactions in euro, rather than the sum of all the transactions in currency, then converted into euros.

Here is a simple example: let's say I have a bank account in USD, and let's say I buy 100 USD when the rate is 1USD = 1 EUR. The credit / debit of the move lines are in EUR, 100 each (and the balance is 100 EUR on the 55 account); and the amount_currency is 100 USD.

Let us say that a few months later, the rate is 1USD = 0.7 EUR. Since I own 100 USD, the asset in the balance sheet (= the balance of the 55 account in USD) should be converted into its current value in EUR, thus 70 (= sum of the "amount_currency" fields, converted with the current rate). But currently it gives 100 EUR (= sum of the "balance" fields, already in EUR).

**Comment by sbidoul** [comment]
I assume you refer to l10n_be_mis_reports? 

Yes this is normal. If mis builder would attempt to do currency conversion for such accounts, the resulting balance would not be... balanced anymore.

Foreign currency revaluations must be posted explicitly (with an unrealized gain loss counterpart). The good news is that there is an excellent OCA module for that: https://github.com/OCA/account-closing/tree/11.0/account_multicurrency_revaluation.

**Comment by fdegrave** [comment]
Indeed I refer to l10n_be_mis_reports, sorry for the omission.

And yes, you are right; now I need to explain this to my CFO ;-) I will have a thorough look at the module you suggest. Thanks a lot!
