### ISSUE TITLE
Migration of vat part of l10n_be_mis_reports to 13.0 and later

### ISSUE THREAD

**Issue by mgielissen** [OCA/l10n-belgium#89]
Are there any plans to migrate l10n_be_mis_reports for Odoo 13.0?

**Comment by sbidoul** [comment]
Hi @mgielissen, MIS Builder data files are fully compatible from 10 to 13. So a migration should be fairly trivial. Anyone doing a PR for this can expect a fast track merge :)

**Comment by sbidoul** [comment]
That said, Odoo did change the way taxes are managed in v13, so the VAT declaration template is going to be more difficult to migrate. P&L and BS reports should migrate without change, since they are based on account code prefixes.

**Comment by debaetsr** [comment]
Is there any progress in this?  If not, I’ll give it a try the next couple of weeks.

The main change I can see, is that invoices are directly written to account.move and account.move.line,  the latter containing the tag_ids used by tax grid. 
There are also changes in the external references in l10n_be.

**Comment by antonclaeys** [comment]
Is there any news here? Can I help in some way (however, i don't really know where to start).
